---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yml
namespace: argo-rollouts
bases:
- https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml