---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yml
namespace: argocd
bases:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
